"use client";

import { useState, useEffect } from 'react';
import { 
  Play, 
  Clock, 
  Calendar, 
  Eye, 
  ThumbsUp, 
  Download, 
  Copy, 
  Share2, 
  Bookmark,
  ChevronLeft,
  ChevronRight,
  Link,
  BarChart3,
  MessageSquare,
  Tag,
  Timer,
  Scissors,
  Volume2,
  Users,
  Globe,
  CheckCircle,
  Loader2,
  ExternalLink,
  AlertCircle
} from 'lucide-react';
import { marked } from 'marked';
import DiscussionTab from './components/DiscussionTab';

// API Configuration
const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';

interface Summary {
  id: string;
  user_id: string;
  video_id: string;
  video_title: string | null;
  channel_name: string | null;
  channel_id: string | null;
  thumbnail_url: string | null;
  duration: string | null;
  views: string | null;
  likes: string | null;
  published_at: Date | null;
  created_at?: Date; // Usually auto-generated by Sequelize
  updated_at?: Date; // Usually auto-generated by Sequelize
  summary: string | null;
  key_points: string[];
  transcript: Array<{ time: string; text: string }>;
  chapters: Array<{ timestamp: string; title: string }>;
  original_word_count: number | null;
  summary_word_count: number | null;
  reduction_percentage: number | null;
  time_saved: string | null;
  tags: string[];
  category: 'Technology' | 'Programming' | 'Business' | 'Education' | 'Entertainment' | 'Other';
  sentiment: 'positive' | 'neutral' | 'negative';
  complexity: 'low' | 'medium' | 'high';
  status: 'processing' | 'completed' | 'failed';
  processing_time: number | null;
  ai_model: string;
  is_public: boolean;
  is_bookmarked: boolean;
  download_count: number;
  share_count: number;
  
  // Association fields (will be populated by Sequelize)
  user?: {
    id: string;
    username: string;
    avatar: string;
    // Add other user fields as needed
  };
}

// You might also want to create a type for the creation attributes (without auto-generated fields)
type SummaryCreationAttributes = Omit<Summary, 'id' | 'created_at' | 'updated_at' | 'download_count' | 'share_count' | 'user'>;

interface ApiResponse {
  success: boolean;
  data: Summary;
  error?: string;
}

// interface PageProps {
//   params: {
//     slug: string;
//   };
// }
interface PageProps {
  params: {
    slug: string[];
  };
  searchParams?: { [key: string]: string | string[] | undefined };
}

const SummaryDetailPage = ({ params }: PageProps) => {
  const [summary, setSummary] = useState<Summary | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState('summary');
  const [isCopied, setIsCopied] = useState(false);
  const [isBookmarked, setIsBookmarked] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  // let { slug } = params;
  let idFromPath = '';

  // Get auth token from localStorage
  const getAuthToken = () => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('token');
    }
    return null;
  };

  // Get auth headers
  const getAuthHeaders = () => {
    const token = getAuthToken();
    return {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`
    };
  };

  // Fetch summary data from API
  useEffect(() => {
    document.title = 'Summary Details - YouTube Summarizer';

    // if (!slug || slug.length === 0) {
    const pathSegments = window.location.pathname.split('/');
    idFromPath = pathSegments[pathSegments.length - 1];
    // }

    console.log('Extracted ID from path:', idFromPath);

    const fetchSummary = async () => {
      // console.log('Fetching summary for slug:', slug);
      try {
        setLoading(true);
        setError(null);
        
        // Get authentication token (adjust based on your auth setup)
        // const token = localStorage.getItem('token');
        // const headers: HeadersInit = {
        //   'Content-Type': 'application/json',
        // };

        // if (token) {
        //   headers['Authorization'] = `Bearer ${token}`;
        // }

        const response = await fetch(`${API_BASE_URL}/api/v1/summaries/${idFromPath}`, {
          headers: getAuthHeaders(),
        });

        // if (!response.ok) {
        //   throw new Error(`Failed to fetch summary: ${response.statusText}`);
        // }

        const result: ApiResponse = await response.json();
        
        if (result.success && result.data) {
          setSummary(result.data);
          document.title = `${result.data.video_title} - Summary Details - YouTube Summarizer`;
        } else {
          throw new Error(result.error || 'Failed to load summary');
        }
      } catch (err) {
        console.error('Error fetching summary:', err);
        setError(err instanceof Error ? err.message : 'An unknown error occurred');
      } finally {
        setLoading(false);
      }
    };

    fetchSummary();
  }, []);

  // Get auth headers for authenticated requests
  // const getAuthHeaders = (): HeadersInit => {
  //   const headers: HeadersInit = {
  //     'Content-Type': 'application/json',
  //   };
    
  //   const token = localStorage.getItem('token');
  //   if (token) {
  //     headers['Authorization'] = `Bearer ${token}`;
  //   }
    
  //   return headers;
  // };

  const handleCopySummary = () => {
    if (!summary) return;
    
    navigator.clipboard.writeText(summary.summary);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleExport = async (format: string) => {
    if (!summary) return;
    
    setIsDownloading(true);
    try {
      const response = await fetch(
        `${API_BASE_URL}/api/v1/summary/${summary.id}/export?format=${format}`,
        {
          headers: getAuthHeaders(),
        }
      );

      if (!response.ok) {
        throw new Error('Export failed');
      }

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `summary-${summary.id}.${format.toLowerCase()}`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err) {
      console.error('Export error:', err);
      alert(`Failed to export as ${format}`);
    } finally {
      setIsDownloading(false);
    }
  };

  const handleBookmarkToggle = async () => {
    if (!summary) return;
    
    try {
      const response = await fetch(
        `${API_BASE_URL}/api/v1/summary/${summary.id}/bookmark`,
        {
          method: isBookmarked ? 'DELETE' : 'POST',
          headers: getAuthHeaders(),
        }
      );

      if (response.ok) {
        setIsBookmarked(!isBookmarked);
      }
    } catch (err) {
      console.error('Bookmark error:', err);
    }
  };

  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', { 
      month: 'short', 
      day: 'numeric',
      year: 'numeric',
      // hour: '2-digit',
      // minute: '2-digit'
    });
  };
  
  function timeAgo(iso) {
    const date = new Date(iso);
    const rtf = new Intl.RelativeTimeFormat("en", { numeric: "auto" });

    const diff = Date.now() - date;
    const seconds = Math.round(diff / 1000);
    const minutes = Math.round(seconds / 60);
    const hours = Math.round(minutes / 60);
    const days = Math.round(hours / 24);
    const months = Math.round(days / 30);
    const years = Math.round(days / 365);

    if (years > 0) return rtf.format(-years, "year");
    if (months > 0) return rtf.format(-months, "month");
    if (days > 0) return rtf.format(-days, "day");
    if (hours > 0) return rtf.format(-hours, "hour");
    if (minutes > 0) return rtf.format(-minutes, "minute");
    return rtf.format(-seconds, "second");
  }


  // Loading state
  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="h-12 w-12 animate-spin text-gray-400 mx-auto mb-4" />
          <p className="text-gray-600 dark:text-gray-300">Loading summary...</p>
        </div>
      </div>
    );
  }

  // Error state
  if (error || !summary) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 p-4 md:p-6">
        <div className="max-w-7xl mx-auto">
          <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg p-6">
            <div className="flex flex-col items-center justify-center py-12">
              <AlertCircle className="h-16 w-16 text-red-500 mb-4" />
              <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-2">
                Unable to Load Summary
              </h2>
              <p className="text-gray-600 dark:text-gray-300 mb-6 text-center">
                {error || 'Summary not found'}
              </p>
              <button 
                onClick={() => window.history.back()}
                className="inline-flex items-center gap-2 bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 text-gray-800 dark:text-gray-200 px-4 py-2 rounded-lg font-medium transition-colors"
              >
                <ChevronLeft className="h-4 w-4" />
                Back to Summaries
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <>
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 p-4 md:p-6">
        {/* Back Navigation */}
        <div className="mb-6">
          <button 
            onClick={() => window.history.back()}
            className="flex items-center gap-2 text-gray-600 dark:text-gray-300 hover:text-gray-800 dark:hover:text-white transition-colors"
          >
            <ChevronLeft className="h-4 w-4" />
            Back to Summaries
          </button>
        </div>

        <div className="max-w-7xl mx-auto space-y-6">
          {/* Header Section */}
          <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg p-6">
            <div className="flex flex-col lg:flex-row gap-6">
              {/* Video Thumbnail */}
              <div className="lg:w-2/5">
                <div className="relative rounded-xl overflow-hidden shadow-lg">
                  <img 
                    src={summary.thumbnail_url || `https://img.youtube.com/vi/${summary.video_id}/hqdefault.jpg`} 
                    alt={summary.video_title}
                    className="w-full aspect-video object-cover"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent flex items-end p-4">
                    <div className="text-white">
                      <div className="flex items-center gap-2 mb-2">
                        <Play className="h-5 w-5" />
                        <span className="text-sm font-medium">Click to watch on YouTube</span>
                      </div>
                    </div>
                  </div>
                </div>
                
                {/* Video Stats */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4">
                  <div className="bg-gray-50 dark:bg-gray-700/50 p-3 rounded-lg text-center">
                    <Clock className="h-5 w-5 text-gray-500 dark:text-gray-400 mx-auto mb-1" />
                    <div className="text-sm font-semibold dark:text-white">{summary.duration}</div>
                    <div className="text-xs text-gray-500 dark:text-gray-400">Duration</div>
                  </div>
                  <div className="bg-gray-50 dark:bg-gray-700/50 p-3 rounded-lg text-center">
                    <Eye className="h-5 w-5 text-gray-500 dark:text-gray-400 mx-auto mb-1" />
                    <div className="text-sm font-semibold dark:text-white">{Number(summary.views).toLocaleString()}</div>
                    <div className="text-xs text-gray-500 dark:text-gray-400">Views</div>
                  </div>
                  <div className="bg-gray-50 dark:bg-gray-700/50 p-3 rounded-lg text-center">
                    <ThumbsUp className="h-5 w-5 text-gray-500 dark:text-gray-400 mx-auto mb-1" />
                    <div className="text-sm font-semibold dark:text-white">{Number(summary.likes).toLocaleString()}</div>
                    <div className="text-xs text-gray-500 dark:text-gray-400">Likes</div>
                  </div>
                  <div className="bg-gray-50 dark:bg-gray-700/50 p-3 rounded-lg text-center">
                    <Timer className="h-5 w-5 text-gray-500 dark:text-gray-400 mx-auto mb-1" />
                    <div className="text-sm font-semibold dark:text-white">{summary.time_saved}</div>
                    <div className="text-xs text-gray-500 dark:text-gray-400">Time Saved</div>
                  </div>
                </div>
              </div>

              {/* Video Info */}
              <div className="lg:w-3/5 space-y-4">
                <div>
                  <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
                    {summary.video_title}
                  </h1>
                  <div className="flex items-center gap-4 text-sm text-gray-600 dark:text-gray-300 mb-4">
                    <div className="flex items-center gap-2">
                      <Users className="h-4 w-4" />
                      <a 
                        href={`https://youtube.com/channel/${summary.channel_id}`}
                        className="hover:text-red-600 dark:hover:text-red-400 transition-colors"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        {summary.channel_name}
                      </a>
                    </div>
                    <div className="flex items-center gap-2">
                      <Calendar className="h-4 w-4" />
                      Published: {formatDate(summary.published_at)}
                    </div>
                    <div className="flex items-center gap-2">
                      <Bookmark className="h-4 w-4" />
                      Summarized: {timeAgo(summary.created_at)}
                    </div>
                    {summary.download_count !== undefined && (
                      <div className="flex items-center gap-2">
                        <Download className="h-4 w-4" />
                        Downloads: {summary.download_count}
                      </div>
                    )}
                  </div>

                  {/* Created by */}
                  {summary.user && (
                    <div className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-300 mb-2">
                      <span>Created by:</span>
                      <div className="flex items-center gap-2">
                        {summary.user.avatar && (
                          <img 
                            src={summary.user.avatar} 
                            alt={summary.user.username}
                            className="h-6 w-6 rounded-full"
                          />
                        )}
                        <span className="font-medium">{summary.user.username}</span>
                      </div>
                    </div>
                  )}
                </div>

                {/* Action Buttons */}
                <div className="flex flex-wrap gap-3">
                  <a
                    href={`https://youtube.com/watch?v=${summary.video_id}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg font-medium transition-colors"
                  >
                    <Play className="h-4 w-4" />
                    Watch on YouTube
                    <ExternalLink className="h-3 w-3" />
                  </a>
                  
                  <button
                    onClick={handleCopySummary}
                    disabled={isCopied}
                    className="inline-flex items-center gap-2 bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 text-gray-800 dark:text-gray-200 px-4 py-2 rounded-lg font-medium transition-colors disabled:opacity-50"
                  >
                    {isCopied ? (
                      <>
                        <CheckCircle className="h-4 w-4 text-green-500" />
                        Copied!
                      </>
                    ) : (
                      <>
                        <Copy className="h-4 w-4" />
                        Copy Summary
                      </>
                    )}
                  </button>
                  
                  <button
                    onClick={handleBookmarkToggle}
                    disabled={isDownloading}
                    className={`inline-flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-colors ${
                      isBookmarked 
                        ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400' 
                        : 'bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 text-gray-800 dark:text-gray-200'
                    }`}
                  >
                    <Bookmark className={`h-4 w-4 ${isBookmarked ? 'fill-current' : ''}`} />
                    {isBookmarked ? 'Bookmarked' : 'Bookmark'}
                  </button>
                  
                  <div className="relative group">
                    <button 
                      disabled={isDownloading}
                      className="inline-flex items-center gap-2 bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 text-gray-800 dark:text-gray-200 px-4 py-2 rounded-lg font-medium transition-colors disabled:opacity-50"
                    >
                      {isDownloading ? (
                        <Loader2 className="h-4 w-4 animate-spin" />
                      ) : (
                        <Download className="h-4 w-4" />
                      )}
                      Export
                      <ChevronRight className="h-3 w-3 rotate-90" />
                    </button>
                    <div className="absolute right-0 mt-2 w-48 bg-white dark:bg-gray-800 rounded-lg shadow-xl border border-gray-200 dark:border-gray-700 invisible group-hover:visible opacity-0 group-hover:opacity-100 transition-all z-10">
                      <div className="py-1">
                        {['PDF', 'Markdown', 'Text', 'Notion'].map((format) => (
                          <button
                            key={format}
                            onClick={() => handleExport(format)}
                            disabled={isDownloading}
                            className="w-full text-left px-4 py-2 text-sm hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors dark:text-white disabled:opacity-50"
                          >
                            Export as {format}
                          </button>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>

                {/* Summary Stats */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3 pt-4 border-t border-gray-200 dark:border-gray-700">
                  <div className="text-center">
                    <div className="text-2xl font-bold text-blue-600 dark:text-blue-400">
                      {summary.reduction_percentage}%
                    </div>
                    <div className="text-xs text-gray-500 dark:text-gray-400">Content Reduced</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-green-600 dark:text-green-400">
                      {summary.summary_word_count}
                    </div>
                    <div className="text-xs text-gray-500 dark:text-gray-400">Summary Words</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-purple-600 dark:text-purple-400">
                      {summary.original_word_count}
                    </div>
                    <div className="text-xs text-gray-500 dark:text-gray-400">Original Words</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-orange-600 dark:text-orange-400">
                      {summary.complexity}
                    </div>
                    <div className="text-xs text-gray-500 dark:text-gray-400">Complexity</div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Rest of the component remains the same */}
          {/* ... (Keep all the existing tab content, related summaries, etc.) ... */}
          
          {/* Main Content Tabs */}
          <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg overflow-hidden">
            {/* Tab Navigation */}
            <div className="border-b border-gray-200 dark:border-gray-700">
              <nav className="flex flex-wrap -mb-px">
                {[
                  { id: 'summary', label: 'AI Summary', icon: MessageSquare },
                  // { id: 'chapters', label: 'Chapters', icon: Scissors },
                  { id: 'transcript', label: 'Transcript', icon: Volume2 },
                  { id: 'AI Discussion', label: 'AI Discussion', icon: Globe },
                  // { id: 'analysis', label: 'Analysis', icon: BarChart3 },
                ].map((tab) => (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id)}
                    className={`flex items-center gap-2 px-6 py-4 text-sm font-medium border-b-2 transition-colors ${
                      activeTab === tab.id
                        ? 'border-red-500 text-red-600 dark:text-red-400'
                        : 'border-transparent text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'
                    }`}
                  >
                    <tab.icon className="h-4 w-4" />
                    {tab.label}
                  </button>
                ))}
              </nav>
            </div>

            {/* Tab Content */}
            <div className="p-6">
              {/* Summary Tab */}
              {activeTab === 'summary' && (
                <div className="space-y-6">
                  {/* Main Summary */}
                  <div className="prose dark:prose-invert max-w-none">
                    <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                      AI-Generated Summary
                    </h3>
                    <p className="text-gray-700 dark:text-gray-300 leading-relaxed" style={{ whiteSpace: 'pre-line' }} dangerouslySetInnerHTML={{ __html: marked.parse(summary.summary ?? "") }}></p>
                  </div>

                  {/* Key Takeaways */}
                  <div>
                    <h4 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                      Key Takeaways
                    </h4>
                    <ul className="space-y-3">
                      {summary.key_points.map((point, index) => (
                        <li key={index} className="flex items-start gap-3">
                          <div className="flex-shrink-0 mt-1">
                            <div className="h-6 w-6 rounded-full bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center">
                              <span className="text-xs font-semibold text-blue-600 dark:text-blue-400">
                                {index + 1}
                              </span>
                            </div>
                          </div>
                          <span className="text-gray-700 dark:text-gray-300" dangerouslySetInnerHTML={{ __html: marked.parse(point ?? "") }}></span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}

              {/* Chapters Tab */}
              {activeTab === 'chapters' && (
                <div className="space-y-4">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                    Video Chapters
                  </h3>
                  <div className="space-y-3">
                    {summary.chapters.map((chapter, index) => (
                      <div
                        key={index}
                        className="flex items-center gap-4 p-4 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors group cursor-pointer"
                      >
                        <div className="flex-shrink-0">
                          <div className="h-10 w-16 rounded bg-gray-200 dark:bg-gray-700 flex items-center justify-center">
                            <Play className="h-4 w-4 text-gray-500 dark:text-gray-400" />
                          </div>
                        </div>
                        <div className="flex-1">
                          <div className="flex items-center justify-between">
                            <div>
                              <span className="text-sm font-mono text-gray-500 dark:text-gray-400">
                                {chapter.timestamp}
                              </span>
                              <h4 className="font-medium text-gray-900 dark:text-white">
                                {chapter.title}
                              </h4>
                            </div>
                            <ChevronRight className="h-4 w-4 text-gray-400 group-hover:text-gray-600 dark:group-hover:text-gray-300 transition-colors" />
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Transcript Tab */}
              {activeTab === 'transcript' && (
                <div>
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                    Full Transcript
                  </h3>
                  <div className="space-y-4 max-h-[400px] overflow-y-auto pr-4">
                    {summary.transcript.map((line, index) => (
                      <div
                        key={index}
                        className="flex gap-4 p-3 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors cursor-pointer"
                      >
                        <div className="flex-shrink-0">
                          <span className="text-sm font-mono text-gray-500 dark:text-gray-400">
                            {line.timestamp}
                          </span>
                        </div>
                        <p className="text-gray-700 dark:text-gray-300">
                          {line.text}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Analysis Tab */}
              {activeTab === 'analysis' && (
                <div className="space-y-6">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                    Content Analysis
                  </h3>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {/* Sentiment Analysis */}
                    <div className="bg-gray-50 dark:bg-gray-700/30 rounded-xl p-4">
                      <h4 className="font-medium text-gray-900 dark:text-white mb-3">
                        Sentiment Analysis
                      </h4>
                      <div className="space-y-3">
                        <div>
                          <div className="flex justify-between text-sm mb-1">
                            <span className='dark:text-white'>Positive</span>
                            <span className='dark:text-white'>65%</span>
                          </div>
                          <div className="h-2 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                            <div className="h-full bg-green-500 rounded-full" style={{ width: '65%' }} />
                          </div>
                        </div>
                        <div>
                          <div className="flex justify-between text-sm mb-1">
                            <span className='dark:text-white'>Neutral</span>
                            <span className='dark:text-white'>25%</span>
                          </div>
                          <div className="h-2 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                            <div className="h-full bg-blue-500 rounded-full" style={{ width: '25%' }} />
                          </div>
                        </div>
                        <div>
                          <div className="flex justify-between text-sm mb-1">
                            <span className='dark:text-white'>Negative</span>
                            <span className='dark:text-white'>10%</span>
                          </div>
                          <div className="h-2 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                            <div className="h-full bg-red-500 rounded-full" style={{ width: '10%' }} />
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Complexity Analysis */}
                    <div className="bg-gray-50 dark:bg-gray-700/30 rounded-xl p-4">
                      <h4 className="font-medium text-gray-900 dark:text-white mb-3">
                        Content Complexity
                      </h4>
                      <div className="space-y-4">
                        <div>
                          <div className="flex justify-between text-sm mb-1">
                            <span className='dark:text-white'>Readability Score</span>
                            <span className="font-semibold text-green-600">8.2/10</span>
                          </div>
                          <div className="text-xs text-gray-500 dark:text-gray-400">
                            Easy to understand for general audience
                          </div>
                        </div>
                        <div>
                          <div className="flex justify-between text-sm mb-1">
                            <span className='dark:text-white'>Technical Depth</span>
                            <span className="font-semibold text-blue-600">Medium</span>
                          </div>
                          <div className="text-xs text-gray-500 dark:text-gray-400">
                            Some technical terms explained
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Keywords */}
                  <div>
                    <h4 className="font-medium text-gray-900 dark:text-white mb-3">
                      Keywords & Tags
                    </h4>
                    <div className="flex flex-wrap gap-2">
                      {summary.tags.map((tag, index) => (
                        <span
                          key={index}
                          className="inline-flex items-center gap-1 bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 px-3 py-1 rounded-full text-sm"
                        >
                          <Tag className="h-3 w-3" />
                          {tag}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>
              )}

              {/* AI Discussion */}
              {activeTab === 'AI Discussion' && (
                <div className="mt-6">
                  <DiscussionTab summaryId={summary.id} summaryTitle={summary.video_title} />
                </div>
              )}

            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default SummaryDetailPage;